services:
  samba:
    image: dockurr/samba:latest
    container_name: samba
    environment:
      NAME: "SHARE"
      USER: "samba"
      PASS: "samba_secret"
    ports:
      - 445:445
    volumes:
      - /workspace/share:/storage
    restart: unless-stopped

  ftp:
    image: delfer/alpine-ftp-server:latest
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    environment:
      - USERS=ftp|Password_Ftp
      - ADDRESS=ftp.site.domain # change to hostname
    volumes:
      - /workspace/share:/ftp
    restart: unless-stopped
